### ISSUE TITLE
R image out of date

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit-ci/runner-image#225]
R 4.3.1 was released recently, we still have R 4.2.1, which is over 6 months old. This is important for R hooks that depend on packages that were updated on CRAN after the R minor release. CRAN only keeps binaries for the last minor release so upon installing the hooks, a source installation is attempted and fails due to some system dependencies for some packages. See also https://github.com/lorenzwalthert/precommit/issues/496#issuecomment-1654513138.

I would help you but I don't manage to figure out how you determined the [checksum in the build script](https://github.com/pre-commit-ci/runner-image/blob/abf0ad4a2eb8342a7d755953c025b11d864b77ce/languages/R/build.sh#L5) from https://www.r-project.org for the current build.

**Comment by asottile** [comment]
the value is determined with `sha256sum`

**Comment by lorenzwalthert** [comment]
Great, thanks. I also removed the R package with System dependencies from my hook repo so the problem of out of date binaries should not exist anymore. Nevertheless it’s good to have an up-to-date R image for pre-commit.ci

**Comment by asottile** [comment]
should be updated now -- just landed a few minutes ago
