### ISSUE TITLE
Add supply chain security using Docker scout

### ISSUE THREAD

**Issue by oleksis** [pre-commit-ci/runner-image#236]
Add to the main workflow `docker scout` or  [Scout Action](https://github.com/docker/scout-action)

`docker scout cves ghcr.io/pre-commit-ci/runner-image:2023-09-02-d10dad3-full`

![image](https://github.com/pre-commit-ci/runner-image/assets/44526468/b624f4de-5d26-4237-8afe-92b9ff8c2990)

**Comment by asottile** [comment]
these cve scanners are all garbage -- they don't understand debian's policies

there aren't any relevant vulnerabilities anyway as this isn't "exposed" like a traditional application (people would just be sabotaging their own runs)
