### ISSUE TITLE
Docker cli is missing in the runner image

### ISSUE THREAD

**Issue by ritwik-g** [pre-commit-ci/runner-image#255]
Some of the pre-commit hooks we use utilises docker command. But looks like it is missing in the runner and causing error. 

I tried to use `language: docker` and it is clear that the `docker` command is missing.

How can I work around this or currently with `pre-commit.ci` won't this be supported? 

https://results.pre-commit.ci/run/github/761150311/1711542003.JCxMK-gORHy2EJ64-hCeEw

<img width="1610" alt="image" src="https://github.com/pre-commit-ci/runner-image/assets/100672805/01566180-c97d-4f19-85a9-31e7a639bea6">

**Comment by asottile** [comment]
please search the issue tracker, it is linked at the bottom of every page
